[build]
  command = "npm run build"
  publish = "dist/samy-mahrous-legal-consaltans/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200